<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Letak extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Letak_model');
        $this->load->library('form_validation');

        $sesi = $this->session->userdata('nama');
        if(empty($sesi)){
            redirect('login');
        }

        $ctrl['ctrl'] = 'letak';
        $this->session->set_userdata($ctrl);
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $cari = urldecode($this->input->get('cari', TRUE));
        $start = intval($this->input->get('start'));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . 'letak/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'letak/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'letak/index.html';
            $config['first_url'] = base_url() . 'letak/index.html';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = TRUE;
        $config['total_rows'] = $this->Letak_model->total_rows($cari);
        $letak = $this->Letak_model->get_limit_data($config['per_page'], $start, $cari);

        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'letak_data' => $letak,
            'isi' => 'letak/letak_list',
            'q' => $q,
            'cari' => $cari,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->load->view('template/index', $data);
    }

    public function read($id) 
    {
        $row = $this->Letak_model->get_by_id($id);
        if ($row) {
            $data = array(
              'kode_letak' => $row->kode_letak,
              'keterangan' => $row->keterangan,
          );
            $this->load->view('letak/letak_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('letak'));
        }
    }

    public function create_action() 
    {

        $data = array(
          'kode_letak' => $this->input->post('kode_letak',TRUE),
          'keterangan' => $this->input->post('keterangan',TRUE),
      );

        $this->Letak_model->insert($data);
        $this->session->set_flashdata('message', 'Create Record Success');
        redirect(site_url('letak'));
    }
    
    public function update($id) 
    {
        $row = $this->Letak_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'isi' => 'letak/letak_form',
                'action' => site_url('letak/update_action'),
                'kode_letak' => set_value('kode_letak', $row->kode_letak),
                'keterangan' => set_value('keterangan', $row->keterangan),
                'stat' => set_value('stat', $row->stat),
            );
            $this->load->view('template/index', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('letak'));
        }
    }
    
    public function update_action() 
    {
        
         
            $data = array(
              'kode_letak' => $this->input->post('kode_letak',TRUE),
              'keterangan' => $this->input->post('keterangan',TRUE),
          );

            $this->Letak_model->update($this->input->post('kode_letak_lama', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('letak'));
    }
    
    public function delete($id) 
    {
        $row = $this->Letak_model->get_by_id($id);

        if ($row) {
            $this->Letak_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('letak'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('letak'));
        }
    }

    public function _rules() 
    {
     $this->form_validation->set_rules('keterangan', 'keterangan', 'trim|required');

     $this->form_validation->set_rules('kode_letak', 'kode_letak', 'trim|required');
     $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
 }

}

/* End of file Letak.php */
/* Location: ./application/controllers/Letak.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-02-03 05:33:50 */
/* http://harviacode.com */