<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Menu_model extends CI_Model
{

    public $table = 'menu';
    public $id = 'idmenu';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all makanan
    function shop_get_all($ktgr)
    {
        $this->db->select('menu.*, warung.nama_warung');
        $this->db->where('kategori', $ktgr);
        $this->db->join('warung','menu.id_warung = warung.idwarung','left');
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get all makanan
    function get_all($ktgr,$usr = NULL)
    {
        $this->db->where('kategori', $ktgr);
        $this->db->where('id_warung', $usr);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->select('menu.*, warung.nama_warung');
        $this->db->join('warung','menu.id_warung = warung.idwarung','left');
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }


    // get data by id
    function get_id_warung($id)
    {
        $this->db->where('pemilik', $id);
        return $this->db->get('warung')->row();
    }
    

    function getmakananfav()
    {
        $this->db->where('kategori','makanan');
        $this->db->limit(10);
        return $this->db->get($this->table)->result();
    }

    // function getcombo()
    // {
    //     $this->db->where('kategori','combo');
    //     return $this->db->get($this->table)->result();
    // }
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idmenu', $q);
        $this->db->or_like('id_warung', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('stock', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get total rows
    function jml_krjng($q) {
        $this->db->where('id_member', $q);
        $this->db->where('keterangan', 'keranjang');
        $this->db->from('keranjang');
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idmenu', $q);
        $this->db->or_like('id_warung', $q);
        $this->db->or_like('nama', $q);
        $this->db->or_like('harga', $q);
        $this->db->or_like('stock', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Makanan_model.php */
/* Location: ./application/models/Makanan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-02-10 08:28:14 */
/* http://harviacode.com */