<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Warung_model extends CI_Model
{

    public $table = 'warung';
    public $id = 'idwarung';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idwarung', $q);
        $this->db->or_like('pemilik', $q);
        $this->db->or_like('nama_warung', $q);
        $this->db->or_like('letak', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get total rows
    function get_jml_produk($q) {
        $this->db->where('id_warung', $q); 
        return $this->db->get('menu')->num_rows();
    }

    // get total rows
    function get_jml_terjual($q) {
       return $this->db->query("SELECT SUM(qtty) as tot FROM `keranjang` JOIN `menu` ON `keranjang`.`idmenu` = `menu`.`idmenu` WHERE `menu`.`id_warung` = '".$q."' AND `keterangan` = 'selesai'")->row();
        // $this->db->join('menu','keranjang.idmenu = menu.idmenu');
        // // $this->db->join('warung','menu.id_warung = warung.pemilik');
        // $this->db->where('menu.id_warung', $q); 
        // $this->db->where('keteranga', 'cekout'); 
        // return $this->db->get('keranjang')->result();
        // return $this->db->count_all_results();
   }

   function get_jml_order($q) {
       return $this->db->query("SELECT COUNT(*) as tot FROM `keranjang` JOIN `menu` ON `keranjang`.`idmenu` = `menu`.`idmenu` WHERE `menu`.`id_warung` = '".$q."' AND `keterangan` = 'cekout'")->row();
   }

   function get_order_by_idwarung($q) {
     // return $this->db->query("SELECT * FROM `keranjang` JOIN `menu` ON `keranjang`.`idmenu` = `menu`.`idmenu` WHERE `menu`.`id_warung` = '".$q."' AND `keterangan` = 'cekout'")->result();

       $this->db->select('keranjang.*, member.nama_lengkap as pemesan, menu.nama, menu.harga, invoice.catatan');
       $this->db->join('menu','menu.idmenu = keranjang.idmenu');
    $this->db->join('member','member.id_member = keranjang.id_member');
       // $this->db->join('warung','menu.id_warung = warung.pemilik');
       $this->db->join('invoice','invoice.kode_invoice = keranjang.kode_invoice');
       $this->db->where('menu.id_warung', $q);
       $this->db->where('keterangan', 'cekout');
       return $this->db->get('keranjang')->result();
   }

    // get data with limit and search
   function get_limit_data($limit = null, $start = 0, $q = NULL) {
    $this->db->select('warung.*, member.nama_lengkap, letak.keterangan');
    $this->db->join('member','member.id_member = warung.pemilik');
    $this->db->join('letak','letak.kode_letak = warung.letak');
    $this->db->order_by($this->id, $this->order);
    $this->db->like('idwarung', $q);
    $this->db->or_like('pemilik', $q);
    $this->db->or_like('nama_warung', $q);
    $this->db->or_like('letak', $q);
    return $this->db->get($this->table)->result();
}

function get_profil($id) {
    $this->db->select('warung.*, member.nama_lengkap, letak.keterangan');
    $this->db->join('member','member.id_member = warung.pemilik');
    $this->db->join('letak','letak.kode_letak = warung.letak');
    $this->db->where('pemilik', $id);
    return $this->db->get($this->table)->row();
}

    // insert data
function insert($data)
{
    $this->db->insert($this->table, $data);
}

    // get data by id member
function cek_warung($id)
{
    $this->db->where('pemilik', $id);
    return $this->db->get('warung')->row();
}

    // update data
function update($id, $data)
{
    $this->db->where($this->id, $id);
    $this->db->update($this->table, $data);
}

    // update data status letak
function statusletak($kd, $data)
{
    $this->db->where('kode_letak', $kd);
    $this->db->update('letak', $data);
}

    // update data role user
function statususer($id, $data)
{
    $this->db->where('id_member', $id);
    $this->db->update('user', $data);
}

    // delete data
function delete($id)
{
    $this->db->where($this->id, $id);
    $this->db->delete($this->table);
}

}

/* End of file Warung_model.php */
/* Location: ./application/models/Warung_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-02-10 09:01:19 */
/* http://harviacode.com */